### ISSUE TITLE
Spaces being added after colons inside strings

### ISSUE THREAD

**Issue by bobbymond** [paulhammond/jp#4]
**Steps to reproduce**
[test.json](https://github.com/user-attachments/files/17748500/test.json)

```
$ cat test.json
{'sample':[{'sample_with_colons':'2024-11-01T07:00:00Z'}], 'sample_with_colons_2': '2024-11-01T07:00:00Z'}
$jp test.json
{
  'sample': [
    {
      'sample_with_colons': '2024-11-01T07: 00: 00Z'
    }
  ],
  'sample_with_colons_2': '2024-11-01T07: 00: 00Z'
}
```

expected:
```
{
  'sample': [
    {
      'sample_with_colons': '2024-11-01T07:00:00Z'
    }
  ],
  'sample_with_colons_2': '2024-11-01T07:00:00Z'
}
```

**Comment by paulhammond** [comment]
I hate to say it but your test file isn't valid JSON. JSON strings use `"` not `'`. The code already does the right thing with colons inside `"` strings, and I just added a test to make sure that remains true in the future.

This issue makes me wonder if it would be useful to add a warning if the JSON is invalid. I might look into that someday but for now I'm going to close this issue out…
